export type {
	APIGatewayAuthorizerEvent as AwsAPIGatewayAuthorizerEvent,
	APIGatewayAuthorizerHandler,
	APIGatewayAuthorizerResult,
	APIGatewayProxyEvent as AwsAPIGatewayProxyEvent,
	APIGatewayProxyEventV2 as AwsAPIGatewayProxyEventV2,
	APIGatewayProxyHandlerV2,
	APIGatewayProxyResult,
	APIGatewayProxyResultV2 as AwsAPIGatewayProxyResultV2,
	Context as LambdaContext,
	DynamoDBRecord as AwsDynamoDBRecord,
	DynamoDBStreamEvent as AwsDynamoDBStreamEvent,
	Handler,
	SNSEvent as AwsSNSEvent,
	SQSEvent as AwsSQSEvent,
	SQSRecord as AwsSQSRecord,
} from 'aws-lambda'
