packages:
  - packages/*

catalog:
  '@ballatech/tsconfig': '^1.2.0'
  '@effect/language-service': '^0.36.0'
  '@effect/platform': ^0.90.8
  '@types/aws-lambda': ^8.10.152
  '@types/node': ^22.18.1
  effect: ^3.17.13

onlyBuiltDependencies:
  - esbuild
  - msgpackr-extract
